### ISSUE TITLE
Rabbitmq Operator Support

### ISSUE THREAD

**Issue by Jonatthu** [ZCube/bitnami-compat#26]
I am currently using the official rabbitmq guide to install it but it would be nicer to have support for the bitnami helm chart since is the one I am planning to use for the official production one and these images from this repository to test in my local macbook.

Also thanks for doing this! I was able to finally give some progress to this local testing thanks to your work.

**Comment by Jonatthu** [comment]
@ZCube  I see some commits related to this and an updated readme, do you want me to test it out or is there remaining work to do on this one?

**Comment by ZCube** [comment]
@Jonatthu I'd appreciate it if you could test it. The binary itself is built with Golang, so I don't think there will be any problems. However, there may be problems because the binaries do not officially release the arm64 binaries.
Currently, we only check whether the images can be built or not. (too many images and I have no experience with this chart)
