### ISSUE TITLE
Build squash image for size reduction.

### ISSUE THREAD

**Issue by ZCube** [ZCube/bitnami-compat#52]
Build squash image for size reduction.

**Comment by ddelange** [comment]
With `--squash`, the overall size on the registry would increase, because overlapping layers can't be shared across images / image versions anymore.

I'm not sure what the default compression level is, but compression method and compression level can be tweaked: https://github.com/moby/buildkit#imageregistry

You can additionally achieve [lazy-pulling](https://github.com/containerd/stargz-snapshotter/blob/main/docs/estargz.md) capabilities if you set estargz+oci-mediatypes like:
```
--output type=...,compression=estargz,compression-level=9,oci-mediatypes=true
```
although I'm not sure if that feature is completely stable.

Regarding sharing layers across builds: to optimize the sharing/re-using there is `cache-to: type=inline` combined with `cache-from type=registry,ref=...` combined with `--pull` in case of upstream security patches. see e.g. https://github.com/actions-runner-controller/releases/pull/3

**Comment by ZCube** [comment]
Bitnami is already using squashed images. 
```
docker inspect bitnami/redis:6.2.10 | jq '.[0].RootFS'
{
  "Type": "layers",
  "Layers": [
    "sha256:bb0dc2a9e4b156523b294481b686606a2a9c048f8c844023e812a7bd7987e90d",
    "sha256:0469306aa3b1df0122ca17a0b982e3d2ac8397486b00b68331bfd6beaf8a7b18"
  ]
}
```
So Bitnami's Dockerfile operates as a single layer, which eliminates duplication of binary capacity due to factors such as permission changes included in the Dockerfile.
The largest case of this is the Discourse image, which has a difference of about 3590.51MB and 2541.46 MB before and after squash.
I don't care about the cache as squash can be applied after the build.

**Comment by ddelange** [comment]
ok awesome and good to know :) thanks!

**Comment by ZCube** [comment]
List of attempts
1. Using docker-squash : https://github.com/ZCube/bitnami-compat/blob/main/scripts/squash.sh
  *  There is a disadvantage that the base image layer is also merged and becomes one layer.
2. Create Dockerfile.Squash for multistage build : https://github.com/ZCube/bitnami-compat/blob/5f99b4f89d464e668d1cf358b210424c4b39f601/cmd/common.go#L276
  * The reason is unknown, but the owner information is lost during the copy process.
  * Researching methods using cache mount and rsync...
